package com.qoohi.backend.api;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.transaction.annotation.Transactional;
import java.util.*;

@RestController @RequestMapping("/api/admin")
public class AdminController {
  private final JdbcTemplate db; public AdminController(JdbcTemplate db){this.db=db;}
  @GetMapping("/overview") public Map<String,Object> overview(){List<Map<String,Object>> all=db.queryForList("SELECT id,full_name,email,whatsapp,role,balance,avatar_url,created_at FROM users ORDER BY full_name");List<Map<String,Object>> groups=new ArrayList<>();groups.add(group("all","All app users",all));for(String role:List.of("parent","teacher","student","iep","institution")){List<Map<String,Object>> members=all.stream().filter(u->role.equals(String.valueOf(u.get("role")))).toList();if(!members.isEmpty())groups.add(group(role,roleLabel(role),members));}return Map.of("users",count("SELECT count(*) FROM users"),"institutions",count("SELECT count(*) FROM institutions"),"students",count("SELECT count(*) FROM school_students"),"teachers",count("SELECT count(*) FROM users WHERE role='teacher'"),"groups",groups,"serviceCharges",db.queryForList("SELECT * FROM service_charges WHERE active=true ORDER BY sort_order,label"));}
  @GetMapping("/users/all") public Map<String,Object> users(){return Map.of("users",db.queryForList("SELECT id,full_name,email,whatsapp,role,balance,avatar_url,created_at FROM users ORDER BY created_at DESC"));}
  @DeleteMapping("/users/{id}") @Transactional public Map<String,Object> deleteUser(@RequestHeader(value="x-admin-key",required=false)String key,@PathVariable long id){requireSuperadmin(key);Map<String,Object>u=first("SELECT id,email,whatsapp FROM users WHERE id=?",id);if(u==null)throw new IllegalArgumentException("User account not found.");String email=value(u.get("email")),phone=digits(value(u.get("whatsapp")));if(email.isBlank()&&phone.isBlank())throw new IllegalArgumentException("This account has no email or WhatsApp number to block.");db.update("INSERT INTO blocked_accounts(email,whatsapp) VALUES(?,?) ON CONFLICT DO NOTHING",email.isBlank()?null:email,phone.isBlank()?null:phone);db.update("UPDATE institutions SET owner_user_id=NULL WHERE owner_user_id=?",id);db.update("DELETE FROM deposits WHERE user_id=?",id);db.update("DELETE FROM withdrawals WHERE user_id=?",id);db.update("DELETE FROM chat_messages WHERE sender_id=? OR recipient_id=?",id,id);db.update("DELETE FROM users WHERE id=?",id);return Map.of("ok",true,"message","Account deleted. Its email and WhatsApp number are permanently blocked.");}
  @GetMapping("/accounts") public Map<String,Object> accounts(@RequestHeader(value="x-admin-key",required=false) String key){Map<String,Object> admin=require(key);return Map.of("accounts",db.queryForList("SELECT id,name,email,is_superadmin,active,created_at FROM admin_accounts ORDER BY created_at"),"isSuperAdmin",Boolean.TRUE.equals(admin.get("is_superadmin")));}
  @PostMapping("/verify-account") public Map<String,Object> verifyAccount(@RequestHeader(value="x-admin-key",required=false) String key,@RequestBody Map<String,Object> body){requireSuperadmin(key);long id=number(body.get("id"));db.update("UPDATE admin_accounts SET active=true WHERE id=? AND is_superadmin=false",id);return Map.of("ok",true,"message","Admin account verified.");}
  @PostMapping("/remove-account") public Map<String,Object> removeAccount(@RequestHeader(value="x-admin-key",required=false) String key,@RequestBody Map<String,Object> body){requireSuperadmin(key);long id=number(body.get("id"));db.update("DELETE FROM admin_accounts WHERE id=? AND is_superadmin=false",id);return Map.of("ok",true,"message","Admin account removed.");}
  @PostMapping("/create-account") public Map<String,Object> createAccount(@RequestHeader(value="x-admin-key",required=false) String key,@RequestBody Map<String,Object> body){requireSuperadmin(key);long total=count("SELECT count(*) FROM admin_accounts");if(total>=5)throw new IllegalArgumentException("The administrator limit of 5 accounts has been reached.");String name=value(body.getOrDefault("name","")),email=value(body.getOrDefault("email","")).toLowerCase(Locale.ROOT);if(name.isBlank()||email.isBlank())throw new IllegalArgumentException("Admin name and email are required.");if(count("SELECT count(*) FROM admin_accounts WHERE lower(email)=lower(?)",email)>0)throw new IllegalArgumentException("An admin account already exists for this email.");if(count("SELECT count(*) FROM blocked_accounts WHERE lower(email)=lower(?)",email)>0)throw new IllegalArgumentException("This email is permanently blocked.");String access=UUID.randomUUID()+"-"+UUID.randomUUID();db.update("INSERT INTO admin_accounts(name,email,access_key,is_superadmin,active) VALUES(?,?,?,false,true)",name,email,access);return Map.of("ok",true,"accessKey",access,"message","Admin account created and activated. The admin can now log in with this email.");}
  @PostMapping(value="/iep-books",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public Map<String,Object> uploadIepBook(@RequestHeader(value="x-admin-key",required=false) String key,@RequestParam int grade,@RequestParam String subject,@RequestParam(required=false,defaultValue="") String title,@RequestParam MultipartFile file) throws Exception {requireSuperadmin(key);if(grade<1||grade>12)throw new IllegalArgumentException("Grade must be between 1 and 12.");if(file.isEmpty())throw new IllegalArgumentException("Choose an IEP book file.");String contentType=file.getContentType()==null?"application/pdf":file.getContentType();if(!contentType.equalsIgnoreCase("application/pdf"))throw new IllegalArgumentException("IEP books must be uploaded as PDF files.");String cleanSubject=subject.trim();String cleanTitle=title.trim().isBlank()?"Grade "+grade+" "+cleanSubject+" IEP Book":title.trim();db.update("INSERT INTO iep_books(grade,subject,title,filename,content_type,content) VALUES(?,?,?,?,?,?) ON CONFLICT(grade,subject) DO UPDATE SET title=excluded.title,filename=excluded.filename,content_type=excluded.content_type,content=excluded.content,created_at=now()",grade,cleanSubject,cleanTitle,file.getOriginalFilename()==null?"iep-book.pdf":file.getOriginalFilename(),contentType,file.getBytes());return Map.of("ok",true,"message","IEP book uploaded.","grade",grade,"subject",cleanSubject);}
  @GetMapping("/ai-settings") public Map<String,Object> aiSettings(@RequestHeader(value="x-admin-key",required=false) String key){requireSuperadmin(key);Integer count=db.queryForObject("SELECT count(*) FROM ai_settings WHERE setting_key='openrouter_api_key'",Integer.class);return Map.of("configured",count!=null&&count>0&&Boolean.TRUE.equals(db.queryForObject("SELECT setting_value <> '' FROM ai_settings WHERE setting_key='openrouter_api_key'",Boolean.class)));}
  @PostMapping("/ai-settings") public Map<String,Object> saveAiSettings(@RequestHeader(value="x-admin-key",required=false) String key,@RequestBody Map<String,Object> body){requireSuperadmin(key);String value=String.valueOf(body.getOrDefault("openrouterApiKey","")).trim();if(value.isBlank())throw new IllegalArgumentException("OpenRouter API key is required.");db.update("INSERT INTO ai_settings(setting_key,setting_value) VALUES('openrouter_api_key',?) ON CONFLICT(setting_key) DO UPDATE SET setting_value=excluded.setting_value,updated_at=now()",value);return Map.of("ok",true,"configured",true);}
  private Map<String,Object> require(String key){List<Map<String,Object>> rows=db.queryForList("SELECT * FROM admin_accounts WHERE access_key=? AND active=true",key==null?"":key);if(rows.isEmpty())throw new IllegalArgumentException("Admin session expired.");return rows.get(0);}
  private void requireSuperadmin(String key){if(!Boolean.TRUE.equals(require(key).get("is_superadmin")))throw new IllegalArgumentException("Superadmin access required.");}
  private Map<String,Object> group(String key,String name,List<Map<String,Object>> members){return Map.of("key",key,"name",name,"count",members.size(),"members",members);}
  private String roleLabel(String role){return switch(role){case "iep"->"IEP users";case "institution"->"Institutions";default->role.substring(0,1).toUpperCase(Locale.ROOT)+role.substring(1)+"s";};}
  private long count(String query,Object...args){Long n=db.queryForObject(query,Long.class,args);return n==null?0:n;}
  private Map<String,Object> first(String query,Object...args){List<Map<String,Object>>rows=db.queryForList(query,args);return rows.isEmpty()?null:rows.get(0);}
  private String value(Object v){return v==null?"":String.valueOf(v).trim();}
  private String digits(String v){return v.replaceAll("\\D","");}
  private long number(Object value){try{return Long.parseLong(String.valueOf(value));}catch(Exception e){throw new IllegalArgumentException("Account id is required.");}}
}
