package com.qoohi.backend.api;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.qoohi.backend.service.AuthService;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.util.UriComponentsBuilder;
import java.net.URI;
import java.net.URLEncoder;
import java.net.http.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;

@RestController @RequestMapping("/api/auth/oauth/google")
public class GoogleOAuthController {
  private final JdbcTemplate db; private final AuthService auth; private final ObjectMapper json; private final String clientId,clientSecret,redirectUri,frontend;
  private final Map<String,State> states=new ConcurrentHashMap<>();
  public GoogleOAuthController(JdbcTemplate db,AuthService auth,ObjectMapper json,@Value("${qoohi.google-client-id:}")String clientId,@Value("${qoohi.google-client-secret:}")String clientSecret,@Value("${qoohi.google-redirect-uri:http://localhost:8080/api/auth/oauth/google/callback}")String redirectUri,@Value("${qoohi.frontend-origin:http://localhost:5000}")String frontend){this.db=db;this.auth=auth;this.json=json;this.clientId=clientId;this.clientSecret=clientSecret;this.redirectUri=redirectUri;this.frontend=frontend;}
  @GetMapping("/start") public org.springframework.http.ResponseEntity<Void> start(@RequestParam(defaultValue="login")String mode,@RequestParam(defaultValue="")String role){if(clientId.isBlank()||clientSecret.isBlank())return redirect("/?oauth_error=Google+OAuth+is+not+configured");String state=UUID.randomUUID().toString();states.put(state,new State(mode,role,System.currentTimeMillis()));String url=UriComponentsBuilder.fromUriString("https://accounts.google.com/o/oauth2/v2/auth").queryParam("client_id",clientId).queryParam("redirect_uri",redirectUri).queryParam("response_type","code").queryParam("scope","openid email profile").queryParam("access_type","offline").queryParam("prompt","select_account").queryParam("state",state).encode().build().toUriString();return org.springframework.http.ResponseEntity.status(302).location(URI.create(url)).build();}
  @GetMapping("/callback") public org.springframework.http.ResponseEntity<Void> callback(@RequestParam(required=false)String code,@RequestParam(required=false)String state,@RequestParam(required=false)String error){State requested=states.remove(state);if(error!=null||code==null||requested==null||System.currentTimeMillis()-requested.created>600000)return redirect("/?oauth_error=Google+sign-in+was+cancelled+or+expired");try{HttpClient http=HttpClient.newHttpClient();String form="code="+enc(code)+"&client_id="+enc(clientId)+"&client_secret="+enc(clientSecret)+"&redirect_uri="+enc(redirectUri)+"&grant_type=authorization_code";String tokenBody=http.send(HttpRequest.newBuilder(URI.create("https://oauth2.googleapis.com/token")).header("Content-Type","application/x-www-form-urlencoded").POST(HttpRequest.BodyPublishers.ofString(form)).build(),HttpResponse.BodyHandlers.ofString()).body();String access=json.readTree(tokenBody).path("access_token").asText("");if(access.isBlank())return redirect("/?oauth_error=Google+token+exchange+failed");String profileBody=http.send(HttpRequest.newBuilder(URI.create("https://www.googleapis.com/oauth2/v3/userinfo")).header("Authorization","Bearer "+access).GET().build(),HttpResponse.BodyHandlers.ofString()).body();JsonNode p=json.readTree(profileBody);String email=auth.normalize(p.path("email").asText());if(email.isBlank())return redirect("/?oauth_error=Google+did+not+return+an+email");Map<String,Object>u=first("SELECT * FROM users WHERE lower(email)=lower(?)",email);String role=requested.role.isBlank()?"parent":requested.role;if(u==null){long id=db.queryForObject("INSERT INTO users(full_name,email,role,avatar_url) VALUES(?,?,?,?) RETURNING id",Long.class,p.path("name").asText("QOOHI User"),email,role,p.path("picture").asText(null));u=first("SELECT * FROM users WHERE id=?",id);}else if("register".equals(requested.mode)&&!role.equals(String.valueOf(u.get("role")))){db.update("UPDATE users SET secondary_roles=concat_ws(',',nullif(secondary_roles,''),?) WHERE id=?",role,u.get("id"));u=first("SELECT * FROM users WHERE id=?",u.get("id"));}UUID session=auth.session(((Number)u.get("id")).longValue(),null);return redirect("/?oauth_token="+enc(session.toString()));}catch(Exception e){return redirect("/?oauth_error=Google+sign-in+failed");}}
  private org.springframework.http.ResponseEntity<Void> redirect(String path){return org.springframework.http.ResponseEntity.status(302).location(URI.create(frontend+path)).build();}private String enc(String s){return URLEncoder.encode(s,StandardCharsets.UTF_8);}private Map<String,Object>first(String q,Object...v){List<Map<String,Object>>r=db.queryForList(q,v);return r.isEmpty()?null:r.get(0);}private record State(String mode,String role,long created){}
}
