package com.qoohi.backend.api;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.qoohi.backend.service.AuthService;
import com.qoohi.backend.service.MapsService;
import com.qoohi.backend.service.NotificationService;
import jakarta.validation.constraints.Email;
import org.springframework.http.ResponseEntity;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.web.bind.annotation.*;
import java.util.*;

@RestController @RequestMapping("/api")
public class InstitutionController {
  private final JdbcTemplate db; private final AuthService auth; private final MapsService maps; private final ObjectMapper json; private final JavaMailSender mail; private final NotificationService notifications; private final String userAppUrl;
  public InstitutionController(JdbcTemplate db,AuthService auth,MapsService maps,ObjectMapper json,JavaMailSender mail,NotificationService notifications,@org.springframework.beans.factory.annotation.Value("${qoohi.user-app-url:http://localhost:5000}") String userAppUrl){this.db=db;this.auth=auth;this.maps=maps;this.json=json;this.mail=mail;this.notifications=notifications;this.userAppUrl=userAppUrl;}

  @PostMapping("/schools/register") public Map<String,Object> register(@RequestBody Map<String,Object> b){
    String email=auth.normalize(str(b,"email")); if(db.queryForObject("SELECT count(*) FROM institutions WHERE email=?",Integer.class,email)>0) throw new IllegalArgumentException("Institution email is already registered.");
    long owner=db.queryForObject("INSERT INTO users(full_name,email,role,whatsapp) VALUES (?,?, 'institution',?) RETURNING id",Long.class,str(b,"name"),email,str(b,"phone")); UUID id=UUID.randomUUID();
    db.update("INSERT INTO institutions(id,name,email,location,phone,school_type,logo_url,motto,latitude,longitude,owner_user_id) VALUES (?,?,?,?,?,?,?,?,?,?,?)",id,str(b,"name"),email,str(b,"location"),str(b,"phone"),defaultValue(b,"school_type","junior"),str(b,"logo_url"),str(b,"motto"),num(b,"latitude"),num(b,"longitude"),owner);
    auth.sendCode(email,"institution_register"); return Map.of("ok",true,"message","Verification code sent to the institution email.");
  }
  @PostMapping("/schools/login") public Map<String,Object> login(@RequestBody Map<String,Object> b){String email=auth.normalize(str(b,"email")); if(db.queryForObject("SELECT count(*) FROM institutions WHERE email=?",Integer.class,email)==0) throw new IllegalArgumentException("Institution account not found."); auth.sendCode(email,"institution_login"); return Map.of("ok",true,"message","Login verification code sent.");}
  @PostMapping("/schools/verify") public Map<String,Object> verify(@RequestBody Map<String,Object> b){Map<String,Object> u; try { u=auth.verify(str(b,"email"),str(b,"code"),"institution_login"); } catch (IllegalArgumentException ignored) { u=auth.verify(str(b,"email"),str(b,"code"),"institution_register"); } Map<String,Object> i=db.queryForMap("SELECT * FROM institutions WHERE email=?",auth.normalize(str(b,"email"))); UUID token=auth.session(((Number)u.get("id")).longValue(),UUID.fromString(i.get("id").toString())); return Map.of("ok",true,"access_token",token.toString(),"institution",i);}
  @PostMapping("/schools/setup") public Map<String,Object> setup(@RequestHeader("Authorization") String h){UUID id=institution(h); db.update("UPDATE institutions SET initialized=true WHERE id=?",id); return Map.of("ok",true,"message","School structure initialized successfully.");}
  @GetMapping("/schools/dashboard") public Map<String,Object> dashboard(@RequestHeader("Authorization") String h){UUID id=institution(h); Map<String,Object> i=db.queryForMap("SELECT * FROM institutions WHERE id=?",id); return Map.of("institution",i,"classes",db.queryForList("SELECT * FROM school_classes WHERE institution_id=? ORDER BY grade,name",id),"students",db.queryForList("SELECT * FROM school_students WHERE institution_id=? ORDER BY full_name",id),"staff",db.queryForList("SELECT u.id,u.full_name,u.email,u.whatsapp,tp.location_label AS location,tp.latitude,tp.longitude,tp.subjects_json FROM institution_staff s JOIN users u ON u.id=s.user_id LEFT JOIN teacher_profiles tp ON tp.user_id=u.id WHERE s.institution_id=? ORDER BY u.full_name",id));}
  @PostMapping("/schools/classes") public Map<String,Object> addClass(@RequestHeader("Authorization") String h,@RequestBody Map<String,Object>b){UUID id=institution(h); db.update("INSERT INTO school_classes(institution_id,grade,name) VALUES(?,?,?)",id,str(b,"grade"),str(b,"name")); return Map.of("ok",true);}
  @PostMapping("/schools/profile") public Map<String,Object> profile(@RequestHeader("Authorization") String h,@RequestBody Map<String,Object>b){UUID id=institution(h); db.update("UPDATE institutions SET name=?,location=?,phone=?,school_type=?,logo_url=?,motto=?,latitude=?,longitude=? WHERE id=?",str(b,"name"),str(b,"location"),str(b,"phone"),defaultValue(b,"school_type","junior"),str(b,"logo_url"),str(b,"motto"),num(b,"latitude"),num(b,"longitude"),id); return Map.of("institution",db.queryForMap("SELECT * FROM institutions WHERE id=?",id));}
  @PostMapping("/schools/students") public Map<String,Object> addStudent(@RequestHeader("Authorization") String h,@RequestBody Map<String,Object>b){UUID institution=institution(h); String email=auth.normalize(str(b,"parent_email"));
    long student=db.queryForObject("INSERT INTO school_students(institution_id,full_name,registration_no,parent_name,parent_email,parent_phone,parent_location,parent_latitude,parent_longitude,grade_key,class_name,current_teacher,underperforming_subjects_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) RETURNING id",Long.class,institution,str(b,"full_name"),str(b,"registration_no"),str(b,"parent_name"),email,str(b,"parent_phone"),str(b,"parent_location"),num(b,"parent_latitude"),num(b,"parent_longitude"),str(b,"grade_key"),str(b,"class_name"),str(b,"teacher"),jsonText(b.get("subjects")));
    Long parent=firstLong("SELECT id FROM users WHERE email=?",email); if(parent==null) parent=db.queryForObject("INSERT INTO users(full_name,email,whatsapp,role,home_location,latitude,longitude) VALUES(?,?,?,'parent',?,?,?) RETURNING id",Long.class,str(b,"parent_name"),email,str(b,"parent_phone"),str(b,"parent_location"),num(b,"parent_latitude"),num(b,"parent_longitude")); db.update("INSERT INTO parent_student_links(parent_user_id,student_id) VALUES(?,?) ON CONFLICT DO NOTHING",parent,student); notifyUser(parent,"student_registered","Learner registered","Your learner was registered by an institution. Sign in to QOOHI: "+userApp()+"",email); return Map.of("ok",true,"student",Map.of("id",student,"invitation_link",userApp()+"?parent="+Base64.getUrlEncoder().encodeToString(email.getBytes())));
  }
  @PostMapping("/schools/staff") public Map<String,Object> addStaff(@RequestHeader("Authorization") String h,@RequestBody Map<String,Object>b){UUID institution=institution(h); String email=auth.normalize(str(b,"email")); Long user=email.isBlank()?null:firstLong("SELECT id FROM users WHERE email=?",email); if(user==null) user=db.queryForObject("INSERT INTO users(full_name,email,whatsapp,role,home_location,latitude,longitude,subjects_json) VALUES(?,?,?,'teacher',?,?,?,?) RETURNING id",Long.class,str(b,"full_name"),email.isBlank()?null:email,str(b,"whatsapp"),str(b,"location"),num(b,"latitude"),num(b,"longitude"),jsonText(b.get("subjects"))); db.update("INSERT INTO teacher_profiles(user_id,location_label,latitude,longitude,subjects_json) VALUES(?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET location_label=excluded.location_label,latitude=excluded.latitude,longitude=excluded.longitude,subjects_json=excluded.subjects_json",user,str(b,"location"),num(b,"latitude"),num(b,"longitude"),jsonText(b.get("subjects"))); db.update("INSERT INTO institution_staff(institution_id,user_id) VALUES(?,?) ON CONFLICT DO NOTHING",institution,user); return Map.of("ok",true);}
  @PostMapping("/schools/students/{student}/recommendations") public Map<String,Object> recommend(@RequestHeader("Authorization") String h,@PathVariable long student,@RequestBody Map<String,Object>b){institution(h); String subject=str(b,"subject"); Map<String,Object>s=db.queryForMap("SELECT * FROM school_students WHERE id=?",student); List<Map<String,Object>> teachers=db.queryForList("SELECT u.id,u.full_name,u.email,u.whatsapp,tp.location_label,tp.latitude,tp.longitude,tp.subjects_json FROM users u JOIN teacher_profiles tp ON tp.user_id=u.id WHERE u.role='teacher' AND tp.available=true"); List<Map<String,Object>> out=new ArrayList<>(); for(Map<String,Object>t:teachers){double score=subjectScore(str(t,"subjects_json"),subject)+locationScore(num(s,"parent_latitude"),num(s,"parent_longitude"),num(t,"latitude"),num(t,"longitude")); if(score>0){db.update("INSERT INTO recommendations(student_id,teacher_user_id,subject,match_score,reason) VALUES(?,?,?,?,?) ON CONFLICT(student_id,teacher_user_id,subject) DO UPDATE SET match_score=excluded.match_score,reason=excluded.reason",student,t.get("id"),subject,score,"Subject and home-location match."); notifyUser(((Number)t.get("id")).longValue(),"teacher_recommendation","Student recommendation","A learner needs support in "+subject+". Open QOOHI: "+userApp(),str(t,"email")); out.add(new HashMap<>(t));}} out.sort((a,b2)->Double.compare(num(b2,"match_score"),num(a,"match_score"))); return Map.of("ok",true,"recommendations",out);}
  @GetMapping("/places/suggest") public Map<String,Object> suggest(@RequestParam String q){return Map.of("suggestions",maps.suggest(q));}
  @PostMapping("/places/details") public Map<String,Object> details(@RequestBody Map<String,Object>b){return Map.of("place",maps.details(str(b,"placeId")));}
  private UUID institution(String h){Map<String,Object>u=auth.user(h); if(u==null||u.get("institution_id")==null)throw new IllegalArgumentException("Institution verification required."); return UUID.fromString(u.get("institution_id").toString());}
  private void notifyUser(long id,String type,String title,String body,String email){db.update("INSERT INTO notifications(user_id,type,title,body) VALUES(?,?,?,?)",id,type,title,body); try{if(email!=null&&!email.isBlank()){SimpleMailMessage m=new SimpleMailMessage();m.setTo(email);m.setSubject(title);m.setText(body);mail.send(m);}}catch(Exception ignored){} String phone=firstText("SELECT whatsapp FROM users WHERE id=?",id); notifications.whatsapp(phone,body);}
  private String firstText(String sql,Object...v){List<String> r=db.query(sql,(rs,n)->rs.getString(1),v);return r.isEmpty()?"":r.get(0);}
  private Long firstLong(String sql,Object...v){List<Long> r=db.query(sql,(rs,n)->rs.getLong(1),v);return r.isEmpty()?null:r.get(0);}
  private String str(Map<String,Object>b,String k){return b.get(k)==null?"":String.valueOf(b.get(k)).trim();} private String defaultValue(Map<String,Object>b,String k,String d){String v=str(b,k);return v.isBlank()?d:v;} private Double num(Map<String,Object>b,String k){Object v=b.get(k);try{return v==null||String.valueOf(v).isBlank()?null:Double.valueOf(String.valueOf(v));}catch(Exception e){return null;}}
  private String jsonText(Object value){try{return value instanceof String s&&s.trim().startsWith("[")?s:json.writeValueAsString(value==null?List.of():value);}catch(Exception e){return "[]";}}
  private double subjectScore(String raw,String subject){return raw.toLowerCase(Locale.ROOT).contains(subject.toLowerCase(Locale.ROOT))?70:0;} private double locationScore(Double a,Double b,Double c,Double d){if(a==null||b==null||c==null||d==null)return 0;double km=Math.sqrt(Math.pow((a-c)*111,2)+Math.pow((b-d)*111,2));return Math.max(0,30-km);} private String userApp(){return userAppUrl;}
}
