package com.qoohi.backend.api;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.qoohi.backend.service.AuthService;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;
import java.time.OffsetDateTime;
import java.util.*;

/** PostgreSQL/Spring compatibility API for the user frontend's former Node routes. */
@RestController @RequestMapping("/api")
public class LegacyUserController {
  private final JdbcTemplate db; private final AuthService auth; private final ObjectMapper json;
  public LegacyUserController(JdbcTemplate db,AuthService auth,ObjectMapper json){this.db=db;this.auth=auth;this.json=json;}

  @PostMapping("/auth/send-code") public Map<String,Object> sendCode(@RequestBody Map<String,Object>b){String email=auth.normalize(s(b,"email"));String mode="login".equals(s(b,"mode"))?"login":"register";if(email.isBlank())throw new IllegalArgumentException("Email is required.");if(blocked(email,normalisePhone(s(b,"whatsapp"))))throw new IllegalArgumentException("This email or WhatsApp number is permanently blocked.");if("login".equals(mode)&&count("SELECT count(*) FROM users WHERE lower(email)=lower(?)",email)==0)throw new IllegalArgumentException("No account found for: "+email);if("register".equals(mode)&&(s(b,"fullName").isBlank()||s(b,"whatsapp").isBlank()))throw new IllegalArgumentException("Full name and WhatsApp number are required.");auth.sendCode(email,mode);db.update("UPDATE auth_codes SET metadata_json=? WHERE id=(SELECT id FROM auth_codes WHERE email=? AND purpose=? ORDER BY created_at DESC LIMIT 1)",jsonText(b),email,mode);return Map.of("ok",true,"message","Verification code sent.","next","verify-code");}
  @PostMapping("/auth/check-roles") public Map<String,Object> roles(@RequestBody Map<String,Object>b){String email=auth.normalize(s(b,"email"));List<Map<String,Object>> rows=db.queryForList("SELECT id,full_name,role,secondary_roles FROM users WHERE lower(email)=lower(?)",email);if(rows.isEmpty())throw new IllegalArgumentException("No account found.");List<Map<String,Object>> out=new ArrayList<>();for(Map<String,Object>u:rows){out.add(Map.of("userId",u.get("id"),"name",u.get("full_name"),"role",u.get("role")));for(String role:safeSplit(u.get("secondary_roles")))out.add(Map.of("userId",u.get("id"),"name",u.get("full_name"),"role",role));}return Map.of("ok",true,"dashboards",out,"single",out.size()==1);}
  @PostMapping("/auth/verify-code") @Transactional
  public Map<String,Object> verify(@RequestBody Map<String,Object> b) {
    String email=auth.normalize(s(b,"email"));
    String mode="login".equals(s(b,"mode"))?"login":"register";
    Map<String,Object> code=auth.verifyCode(email,s(b,"code"),mode);
    Map<String,Object> meta=parse((String)code.get("metadata_json"));
    Map<String,Object> user=first("SELECT * FROM users WHERE lower(email)=lower(?)",email);
    String requested=Set.of("teacher","parent","iep").contains(s(meta,"registrationType"))?s(meta,"registrationType"):"student";
    if(user==null) {
      long id=db.queryForObject(
        "INSERT INTO users(full_name,email,whatsapp,role,referral_code) VALUES(?,?,?,?,?) RETURNING id",
        Long.class,s(meta,"fullName"),email,s(meta,"whatsapp"),requested,
        "QH"+UUID.randomUUID().toString().replace("-","").substring(0,6).toUpperCase()
      );
      user=first("SELECT * FROM users WHERE id=?",id);
    } else if("register".equals(mode)&&!requested.equals(s(user,"role"))&&!safeSplit(user.get("secondary_roles")).contains(requested)) {
      db.update("UPDATE users SET secondary_roles=concat_ws(',',nullif(secondary_roles,''),?) WHERE id=?",requested,user.get("id"));
      user=first("SELECT * FROM users WHERE id=?",user.get("id"));
    }
    if("register".equals(mode)&&"student".equals(s(meta,"registrationType"))) {
      db.update("UPDATE users SET grade_level=?,subjects_json=? WHERE id=?",
        s(meta,"gradeLevel"),jsonText(allowedCourseInterests(meta.get("courseInterests"))),user.get("id"));
      user=first("SELECT * FROM users WHERE id=?",user.get("id"));
    }
    if("course".equals(s(meta,"registrationType"))&&!s(meta,"selectedPackage").isBlank())
      db.update("INSERT INTO enrollments(user_id,package_key,package_name,price_ksh) VALUES(?,?,?,?) ON CONFLICT DO NOTHING",
        user.get("id"),s(meta,"selectedPackage"),s(meta,"selectedPackage"),0);
    UUID token=auth.session(((Number)user.get("id")).longValue(),null);
    return Map.of("ok",true,"sessionToken",token.toString(),"dashboard",dashboard(user,s(b,"selectedRole")));
  }

  @GetMapping("/student/dashboard") public Map<String,Object> dashboard(@RequestHeader("Authorization")String h,@RequestParam(required=false)String role){Map<String,Object>u=required(h);return Map.of("ok",true,"dashboard",dashboard(u,role));}
  @GetMapping("/teacher/overview") public Map<String,Object> teacherOverview(@RequestHeader("Authorization")String h){Map<String,Object>u=required(h);if(!"teacher".equals(u.get("role")))throw new IllegalArgumentException("Unauthorized.");return Map.of("ok",true,"children",db.queryForList("SELECT DISTINCT p.*,u.full_name parent_name,u.email parent_email,u.whatsapp parent_whatsapp FROM teacher_class_members m JOIN teacher_classes c ON c.id=m.class_id JOIN parent_students p ON m.learner_type='parent_child' AND p.id=m.learner_id JOIN users u ON u.id=p.parent_user_id WHERE c.teacher_id=? ORDER BY p.grade_level,p.child_name",u.get("id")),"teachers",db.queryForList("SELECT id,full_name FROM users WHERE id=? AND role='teacher'",u.get("id")),"currentTeacher",u);}
  @PostMapping("/teacher/children/iep") public Map<String,Object> teacherIep(@RequestHeader("Authorization")String h,@RequestBody Map<String,Object>b){Map<String,Object>u=required(h);if(!"teacher".equals(u.get("role")))throw new IllegalArgumentException("Unauthorized.");if(db.update("UPDATE parent_students p SET assessment_status=?,performance_level=? WHERE p.id=? AND EXISTS (SELECT 1 FROM teacher_class_members m JOIN teacher_classes c ON c.id=m.class_id WHERE c.teacher_id=? AND m.learner_type='parent_child' AND m.learner_id=p.id)",s(b,"assessmentStatus"),s(b,"performanceLevel"),b.get("childId"),u.get("id"))==0)throw new IllegalArgumentException("Learner is not enrolled in one of your classes.");return Map.of("ok",true);}
  @PostMapping("/teacher/specializations") public Map<String,Object> specializations(@RequestHeader("Authorization")String h,@RequestBody Map<String,Object>b){Map<String,Object>u=required(h);db.update("UPDATE users SET specializations=? WHERE id=?",s(b,"specializations"),u.get("id"));return Map.of("ok",true,"specializations",s(b,"specializations"));}
  @PostMapping("/parent/children") public Map<String,Object> child(@RequestHeader("Authorization")String h,@RequestBody Map<String,Object>b){Map<String,Object>u=required(h);db.update("INSERT INTO parent_students(parent_user_id,child_name,grade_level,goals,subjects_json) VALUES(?,?,?,?,?)",u.get("id"),s(b,"childName"),s(b,"gradeLevel"),s(b,"goals"),jsonText(allowedCourseInterests(b.get("courseInterests"))));return Map.of("ok",true,"children",db.queryForList("SELECT * FROM parent_students WHERE parent_user_id=? ORDER BY created_at DESC",u.get("id")));}

  @GetMapping("/user/profile") public Map<String,Object> profile(@RequestHeader("Authorization")String h){Map<String,Object>u=required(h);return Map.of("user",u,"balance",num(u,"balance"));}
  @PostMapping("/user/profile") public Map<String,Object> updateProfile(@RequestHeader("Authorization")String h,@RequestBody Map<String,Object>b){Map<String,Object>u=required(h);db.update("UPDATE users SET full_name=?,whatsapp=?,avatar_url=? WHERE id=?",s(b,"fullName"),s(b,"whatsapp"),s(b,"avatarUrl"),u.get("id"));return Map.of("ok",true,"user",first("SELECT * FROM users WHERE id=?",u.get("id")));}
  @GetMapping("/user/balance") public Map<String,Object> balance(@RequestHeader("Authorization")String h){Map<String,Object>u=required(h);return Map.of("balance",num(u,"balance"));}
  @PostMapping("/user/service/use") public Map<String,Object> service(@RequestHeader("Authorization")String h,@RequestBody Map<String,Object>b){Map<String,Object>u=required(h);double charge=charge(s(b,"serviceKey"));if(charge<0)throw new IllegalStateException("Service charge cannot be negative.");int updated=db.update("UPDATE users SET balance=balance-? WHERE id=? AND balance>=?",charge,u.get("id"),charge);if(updated==0)throw new IllegalArgumentException("Insufficient balance.");Map<String,Object>current=first("SELECT balance FROM users WHERE id=?",u.get("id"));return Map.of("ok",true,"charge",charge,"balance",num(current,"balance"));}
  @PostMapping("/withdraw/request") public Map<String,Object> withdraw(@RequestHeader("Authorization")String h,@RequestBody Map<String,Object>b){Map<String,Object>u=required(h);double amount=Double.parseDouble(s(b,"amount"));if(num(u,"balance")<amount)throw new IllegalArgumentException("Insufficient balance.");db.update("INSERT INTO withdrawals(user_id,amount,mpesa_name,mpesa_number) VALUES(?,?,?,?)",u.get("id"),amount,s(b,"mpesaName"),s(b,"mpesaNumber"));return Map.of("ok",true,"message","Withdrawal request submitted.");}
  @PostMapping("/referral/apply") public Map<String,Object> referral(@RequestHeader("Authorization")String h,@RequestBody Map<String,Object>b){Map<String,Object>u=required(h);Map<String,Object>ref=first("SELECT id FROM users WHERE referral_code=?",s(b,"referralCode"));if(ref==null)throw new IllegalArgumentException("Referral code not found.");if(String.valueOf(ref.get("id")).equals(String.valueOf(u.get("id"))))throw new IllegalArgumentException("You cannot apply your own referral code.");if(db.update("UPDATE users SET referred_by=? WHERE id=? AND referred_by IS NULL",ref.get("id"),u.get("id"))==0)throw new IllegalArgumentException("A referral code has already been applied to this account.");return Map.of("ok",true);}
  @GetMapping("/referral/info") public Map<String,Object> referralInfo(@RequestHeader("Authorization")String h){Map<String,Object>u=required(h);return Map.of("referralCode",s(u,"referral_code"),"referredUsers",count("SELECT count(*) FROM users WHERE referred_by=?",u.get("id")));}

  @GetMapping("/chat/messages") public Map<String,Object> messages(@RequestHeader("Authorization")String h,@RequestParam("with")long with){Map<String,Object>u=required(h);db.update("UPDATE chat_messages SET read_at=now() WHERE recipient_id=? AND sender_id=?",u.get("id"),with);return Map.of("messages",db.queryForList("SELECT c.*,a.full_name from_name,b.full_name to_name FROM chat_messages c JOIN users a ON a.id=c.sender_id JOIN users b ON b.id=c.recipient_id WHERE (sender_id=? AND recipient_id=?) OR (sender_id=? AND recipient_id=?) ORDER BY c.created_at",u.get("id"),with,with,u.get("id")));}
  @PostMapping("/chat/send") public Map<String,Object> sendMessage(@RequestHeader("Authorization")String h,@RequestBody Map<String,Object>b){Map<String,Object>u=required(h);db.update("INSERT INTO chat_messages(sender_id,recipient_id,body) VALUES(?,?,?)",u.get("id"),b.get("toUserId"),s(b,"message"));return Map.of("ok",true);}
  @GetMapping("/chat/unread") public Map<String,Object> unread(@RequestHeader("Authorization")String h){Map<String,Object>u=required(h);return Map.of("notifications",db.queryForList("SELECT c.*,u.full_name from_name FROM chat_messages c JOIN users u ON u.id=c.sender_id WHERE recipient_id=? AND read_at IS NULL ORDER BY created_at DESC",u.get("id")));}
  @GetMapping("/public/teachers") public Map<String,Object> teachers(){return Map.of("ok",true,"teachers",db.queryForList("SELECT id,full_name,COALESCE(NULLIF(specializations,''),NULLIF(subjects_json,''),'[]') AS specializations FROM users WHERE role='teacher' ORDER BY full_name"));}
  @GetMapping("/health") public Map<String,Object> health(){db.queryForObject("SELECT 1",Integer.class);return Map.of("ok",true,"database","postgresql");}

  private Map<String,Object> dashboard(Map<String,Object>u,String requested){String baseRole=s(u,"role");String role=requested==null||requested.isBlank()?baseRole:requested;Map<String,Object>student=new LinkedHashMap<>();student.put("id",u.get("id"));student.put("fullName",u.get("full_name"));student.put("email",u.get("email"));student.put("whatsapp",u.get("whatsapp"));student.put("role",role);student.put("balance",num(u,"balance"));student.put("referralCode",u.get("referral_code"));student.put("avatarUrl",u.get("avatar_url"));student.put("specializations",u.get("specializations"));List<Map<String,Object>> dashboards=new ArrayList<>();dashboards.add(Map.of("role",baseRole,"name",s(u,"full_name")));for(String secondary:safeSplit(u.get("secondary_roles")))if(!secondary.equals(baseRole))dashboards.add(Map.of("role",secondary,"name",s(u,"full_name")));Map<String,Object>out=new LinkedHashMap<>();out.put("student",student);out.put("enrollments",db.queryForList("SELECT * FROM enrollments WHERE user_id=? ORDER BY created_at DESC",u.get("id")));out.put("children",db.queryForList("SELECT * FROM parent_students WHERE parent_user_id=? ORDER BY created_at DESC",u.get("id")));out.put("deposits",db.queryForList("SELECT * FROM deposits WHERE user_id=? ORDER BY created_at DESC LIMIT 10",u.get("id")));out.put("withdrawals",db.queryForList("SELECT * FROM withdrawals WHERE user_id=? ORDER BY created_at DESC LIMIT 10",u.get("id")));out.put("serviceCharges",db.queryForList("SELECT * FROM service_charges WHERE active=true ORDER BY sort_order,label"));out.put("availableDashboards",dashboards);return out;}
  private Map<String,Object> required(String h){Map<String,Object>u=auth.user(h);if(u==null)throw new IllegalArgumentException("Session expired.");return u;}
  private List<String> allowedCourseInterests(Object interests){if(!(interests instanceof List<?> list))return List.of();return list.stream().map(String::valueOf).filter(Set.of("Cybersecurity","Python","Web Design/Website","Computer Packages")::contains).distinct().toList();}
  private Map<String,Object> first(String q,Object...v){List<Map<String,Object>>r=db.queryForList(q,v);return r.isEmpty()?null:r.get(0);}private long count(String q,Object...v){Long n=db.queryForObject(q,Long.class,v);return n==null?0:n;}private String s(Map<String,Object>m,String k){Object v=m.get(k);return v==null?"":String.valueOf(v).trim();}private String normalisePhone(String value){return value==null?"":value.replaceAll("\\D","");}private boolean blocked(String email,String phone){return count("SELECT count(*) FROM blocked_accounts WHERE lower(coalesce(email,''))=lower(?) OR coalesce(whatsapp,'')=?",email,phone)>0;}private double num(Map<String,Object>m,String k){Object v=m.get(k);try{return v==null?0:Double.parseDouble(String.valueOf(v));}catch(Exception e){return 0;}}private List<String> safeSplit(Object v){return v==null?List.of():Arrays.stream(String.valueOf(v).split(",")).map(String::trim).filter(x->!x.isBlank()).toList();}private Map<String,Object>parse(String v){try{return json.readValue(v==null?"{}":v,new TypeReference<>(){});}catch(Exception e){return Map.of();}}private String jsonText(Object v){try{return json.writeValueAsString(v);}catch(Exception e){return "{}";}}private double charge(String key){List<Double>r=db.query("SELECT charge_ksh FROM service_charges WHERE service_key=? AND active=true",(rs,n)->rs.getDouble(1),key);return r.isEmpty()?0:r.get(0);}
}
